# Generated by Django 5.1.5 on 2025-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='created_by',
        ),
        migrations.AddField(
            model_name='challenge',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('not-started', 'Not Started')], default='not-started', max_length=11),
        ),
        migrations.AddField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=6),
        ),
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(to='challenges.tag'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
